### ISSUE TITLE
add ~/.terraformrc to README.md

### ISSUE THREAD

**Issue by kbroughton** [finn-no/terraform-provider-softlayer#3]
as per https://www.terraform.io/docs/plugins/basics.html

I needed to add to ~/.terraformrc
providers {
    softlayer = "$GOPATH/bin/terraform-provider-softlayer"
}

Otherwise terraform plan fails as follows:
(master)][conda_py2] terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:
- 1 error(s) occurred:
- softlayer_ssh_key.default: provider softlayer couldn't be found

**Comment by eirslett** [comment]
Thanks, I updated the readme now!
