### ISSUE TITLE
keypair_id error

### ISSUE THREAD

**Issue by kbroughton** [finn-no/terraform-provider-softlayer#4]
In the past, i've found I have to go into the softlayer GUI to obtain the numeric keypair id for a key with a given name.  Does terraform-provider-softlayer have a mechanism to do this?

The error below comes from ssh_keys = ["${softlayer_ssh_key.my_key.keypair_id}"]
and when I replaced it with a valid SL keypair name i got an error that it should be an int.

As is, I get
(master)][conda_py2] terraform apply
Error creating plan: 1 error(s) occurred:
- 1 error(s) occurred:
- Resource 'softlayer_ssh_key.my_key' does not have attribute 'keypair_id' for variable 'softlayer_ssh_key.my_key.keypair_id'

**Comment by eirslett** [comment]
Yes, it should get the numeric ID from the SoftLayer API, so you won't have to access the GUI. There's a bug in the example, I think... let me look into it!

**Comment by eirslett** [comment]
Aah, it's called "id", not "keypair_id". Sorry!
