### ISSUE TITLE
SSH_KEY already exists

### ISSUE THREAD

**Issue by kbroughton** [finn-no/terraform-provider-softlayer#5]
This is my first forray into terraform.  I'm coming from ansible where I expect plays to be idempotent.

Following the github.com/hashicorp/terraform thread I changed the public_key to a file lookup
resource "softlayer_ssh_key" "my_key" {
    name = "kbroughton_id_rsa.pub"
    public_key = "${file(\"~/.ssh/id_rsa.pub\")}"
}

where kbroughton_id-rsa.pub was previously uploaded by me to softlayer and the id_rsa.pub key exists on my local drive.

With the public_key as a string:
(venv)[kestenbroughton@ip-192-168-1-126:/tmp/sl_terraform][conda_py2] terraform apply
softlayer_ssh_key.my_key: Creating...
  fingerprint: "" => "<computed>"
  name:        "" => "kbroughton_id_rsa.pub"
  public_key:  "" => "~/.ssh/id_rsa.pub"
Error applying plan:

1 error(s) occurred:
- softlayer_ssh_key.my_key: Error creating SSH Key: Unable to generate a fingerprint. Please ensure the key provided is a valid public key.

---

with the public key as a file lookup

(venv)[kestenbroughton@ip-192-168-1-126:/tmp/sl_terraform][conda_py2] terraform apply
softlayer_ssh_key.my_key: Creating...
  fingerprint: "" => "<computed>"
  name:        "" => "kbroughton_id_rsa.pub"
  public_key:  "" => "ssh-rsa AAAAB3Nza<redacted>VeKpH kestenbroughton@mymac.local\n"
Error applying plan:

1 error(s) occurred:
- softlayer_ssh_key.my_key: Error creating SSH Key: SSH key already exists.

This error persists if i change the name kbroughton_id_rsa.pub to something that doesn't exist on SL or if i specify a local key path that does not exist.

Could you clarify if i'm supposed to be using a local keypair that already exists and whether or not I need to have the pubkey already uploaded to SL.

**Comment by eirslett** [comment]
You're supposed to use a local keypair which is not already uploaded to SL - they're (a bit too?) strict on that. What I usually do is to create a new, unique key pair for every terraform deployment.
